FROM golang:1.23-alpine AS builder

WORKDIR /build
COPY . .

RUN apk add --no-cache gcc musl-dev
RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux go build -o /build/app .

FROM alpine:latest

WORKDIR /app
RUN apk --no-cache add ca-certificates postgresql-client

COPY --from=builder /build/app ./app
COPY migrations/ ./migrations/
RUN chmod +x ./app
RUN mkdir -p assets

EXPOSE 8080
CMD ["./app"]
